#!/usr/bin/env python3
"""B-00 denominator / eligibility worked examples (deterministic throw-away calculation).

Evidence only - this script does NOT ship. It encodes a small fact set in the *frozen*
vocabulary of docs/evolune/v1.7/V17_B_00_INSIGHTS_SEMANTICS.md and derives every number by rule,
so a reviewer can re-run it and compare the output with the recorded denominator-examples.md:

    python3 denominator-examples.py        # writes denominator-examples.md (UTF-8) and prints it
"""

from collections import Counter, OrderedDict

# ---------------------------------------------------------------------------
# Fact set: range 2025-01-01 .. 2025-01-07 inclusive, current plan = daily 23:00
# ---------------------------------------------------------------------------
FACTS = [
    dict(kind="matched", provenance="EXACT_SLOT_AND_LOCAL_DATE", source="REMINDER", display_date="2025-01-01", dose=2.0, identity="E2"),
    dict(kind="matched", provenance="EXACT_SLOT_AND_LOCAL_DATE", source="REMINDER", display_date="2025-01-02", dose=2.0, identity="E2"),
    dict(kind="matched", provenance="EXACT_SLOT_AND_LOCAL_DATE", source="WIDGET", display_date="2025-01-03", dose=2.0, identity="E2"),
    dict(kind="matched", provenance="EXACT_SLOT_AND_LOCAL_DATE", source="WEAR", display_date="2025-01-04", dose=2.0, identity="E2"),
    # modern quick record (null slot, manual) matched by the time window -> MEDIUM inferred
    dict(kind="matched", provenance="NULL_SLOT_TIME_WINDOW", source="MANUAL", display_date="2025-01-05", dose=2.0, identity="E2"),
    # null-slot same-day -> LOW inferred
    dict(kind="matched", provenance="NULL_SLOT_SAME_DAY", source="MANUAL", display_date="2025-01-06", dose=1.0, identity="EV"),
    # occurrence without any matching record
    dict(kind="unrecorded", provenance=None, source=None, display_date="2025-01-07", dose=2.0, identity="E2"),
    # unmatched authoritative intakes (no occurrence binding)
    dict(kind="unmatched", provenance=None, source="MANUAL", display_date="2025-01-03", dose=5.0, identity="EV"),
    dict(kind="unmatched", provenance=None, source="LEGACY", display_date="2025-01-02", dose=1.0, identity="E2"),
    # not a HistoricalEntry (upcoming context) - must never enter any history metric
    dict(kind="future", provenance=None, source=None, display_date="2025-01-08", dose=2.0, identity="E2"),
]

TIER = {
    "EXACT_SLOT_AND_LOCAL_DATE": "HIGH",
    "SLOT_WINDOW_WITHOUT_LOCAL_DATE": "MEDIUM",
    "NULL_SLOT_TIME_WINDOW": "MEDIUM",
    "NULL_SLOT_SAME_DAY": "LOW",
}

START, END = "2025-01-01", "2025-01-07"
IN_RANGE = [f for f in FACTS if f["kind"] != "future" and START <= f["display_date"] <= END]
RECORDED = [f for f in IN_RANGE if f["kind"] in ("matched", "unmatched")]
DAYS_WITH_RECORDED = sorted({f["display_date"] for f in RECORDED})
BY_SOURCE = Counter(f["source"] for f in RECORDED)
WITH_RECORD = [f for f in IN_RANGE if f["kind"] == "matched"]
WITHOUT_RECORD = [f for f in IN_RANGE if f["kind"] == "unrecorded"]
CONFIDENCE = Counter(TIER[f["provenance"]] for f in IN_RANGE if f["kind"] == "matched")
CONFIDENCE["NONE"] = len([f for f in IN_RANGE if f["kind"] == "unmatched"])
CONFIDENCE["n/a (no record)"] = len(WITHOUT_RECORD)

DOSE_BY_IDENTITY = OrderedDict()
for fact in RECORDED:
    key = fact["identity"] if fact["identity"] in ("E2", "EB", "EV", "EC", "EN") else "Unknown"
    DOSE_BY_IDENTITY[key] = DOSE_BY_IDENTITY.get(key, 0.0) + fact["dose"]


def ratio(approved_tiers):
    """The frozen (but NOT shipped) section-12 definition, evaluated for evidence."""
    numerator = [f for f in IN_RANGE if f["kind"] == "matched" and TIER[f["provenance"]] in approved_tiers]
    denominator = numerator + WITHOUT_RECORD
    excluded = {
        "unmatched intakes": len([f for f in IN_RANGE if f["kind"] == "unmatched"]),
        "matched below approved tiers": len(
            [f for f in IN_RANGE if f["kind"] == "matched" and TIER[f["provenance"]] not in approved_tiers]
        ),
        "future occurrences": len([f for f in FACTS if f["kind"] == "future"]),
    }
    return len(numerator), len(denominator), excluded


def main():
    print("# B-00 denominator / eligibility worked examples (generated by denominator-examples.py)")
    print()
    print("Range: %s .. %s inclusive (LocalDate), 7 days, current plan = daily 23:00" % (START, END))
    print("Facts in range: %d (excluded future-context rows: %d)" % (len(IN_RANGE), len(FACTS) - len(IN_RANGE)))
    print()
    print("## Shipped metrics (facts only, V17_B_00_INSIGHTS_SEMANTICS section 17)")
    print("- Recorded intakes (matched + unmatched, one per authoritative event): %d" % len(RECORDED))
    print("- Days with recorded intake (unrecorded-only days excluded): %d -> %s"
          % (len(DAYS_WITH_RECORDED), ", ".join(DAYS_WITH_RECORDED)))
    print("- By source: %s" % ", ".join("%s=%d" % kv for kv in sorted(BY_SOURCE.items())))
    print("- Dose totals by medication identity (mg): %s"
          % ", ".join("%s=%.1f" % kv for kv in DOSE_BY_IDENTITY.items()))
    print("- Record coverage (counts, no percentage): occurrences with matching record=%d, without=%d"
          % (len(WITH_RECORD), len(WITHOUT_RECORD)))
    print("- Binding confidence breakdown: %s" % ", ".join("%s=%d" % kv for kv in sorted(CONFIDENCE.items())))
    print()
    print("## Frozen section-12 ratio (NOT shipped in v1.7-B), evaluated for evidence")
    for tiers in ({"HIGH"}, {"HIGH", "MEDIUM"}):
        numerator, denominator, excluded = ratio(tiers)
        print("- approvedTiers={%s}: numerator=%d denominator=%d -> %.1f%%  (excluded: %s)"
              % ("+".join(sorted(tiers)), numerator, denominator, 100.0 * numerator / denominator,
                 ", ".join("%s=%d" % kv for kv in sorted(excluded.items()))))
    print()
    print("## Forbidden formulations (sections 6/18) checked against the same fact set")
    print("- missedCount = unrecordedCount would report %d 'missed' doses: FORBIDDEN "
          "(no recorded intake does not mean not taken)" % len(WITHOUT_RECORD))
    print("- adherence = recorded/(recorded+unrecorded) would report %.1f%%: FORBIDDEN "
          "(the denominator is generated from the current plan, not a historical prescription)"
          % (100.0 * len(WITH_RECORD) / (len(WITH_RECORD) + len(WITHOUT_RECORD))))
    print("- unmatched intakes (%d) must stay out of any plan-based denominator while still counting "
          "as recorded intakes" % len([f for f in IN_RANGE if f["kind"] == "unmatched"]))


if __name__ == "__main__":
    import contextlib
    import io

    buffer = io.StringIO()
    with contextlib.redirect_stdout(buffer):
        main()
    text = buffer.getvalue()
    io.open("denominator-examples.md", "w", encoding="utf-8", newline="\n").write(text)
    print(text)
