package io.github.yingqiu0871.evolune.ui.theme
import androidx.compose.ui.graphics.Color

// v1.7.2 Slice B: the released v1.7.1 standard built-in role constants were removed together
// with the inline lightScheme/darkScheme; the single authority is now the shared
// `theme.palette.LegacyBuiltinTheme` (see ui/theme/PresetColorSchemes.kt). The medium/high
// contrast tables below remain untouched and unused (pre-existing, out of scope).

val primaryLightMediumContrast = Color(0xFF003E3A)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF1A7A73)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF223B38)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF58726F)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF1E3850)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF566F8A)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF4FBF9)
val onBackgroundLightMediumContrast = Color(0xFF161D1C)
val surfaceLightMediumContrast = Color(0xFFF4FBF9)
val onSurfaceLightMediumContrast = Color(0xFF0C1212)
val surfaceVariantLightMediumContrast = Color(0xFFDAE5E2)
val onSurfaceVariantLightMediumContrast = Color(0xFF2E3837)
val outlineLightMediumContrast = Color(0xFF4A5453)
val outlineVariantLightMediumContrast = Color(0xFF656F6D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3231)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F0)
val inversePrimaryLightMediumContrast = Color(0xFF81D5CD)
val surfaceDimLightMediumContrast = Color(0xFFC1C8C6)
val surfaceBrightLightMediumContrast = Color(0xFFF4FBF9)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F3)
val surfaceContainerLightMediumContrast = Color(0xFFE3E9E8)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDC)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCCD3D1)

val primaryLightHighContrast = Color(0xFF00322F)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF00534E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF17302E)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF354E4B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF132E45)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF324B64)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF4FBF9)
val onBackgroundLightHighContrast = Color(0xFF161D1C)
val surfaceLightHighContrast = Color(0xFFF4FBF9)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDAE5E2)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF242E2D)
val outlineVariantLightHighContrast = Color(0xFF414B4A)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3231)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFF81D5CD)
val surfaceDimLightHighContrast = Color(0xFFB4BAB8)
val surfaceBrightLightHighContrast = Color(0xFFF4FBF9)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF2F0)
val surfaceContainerLightHighContrast = Color(0xFFDDE4E2)
val surfaceContainerHighLightHighContrast = Color(0xFFCFD6D4)
val surfaceContainerHighestLightHighContrast = Color(0xFFC1C8C6)

val primaryDarkMediumContrast = Color(0xFF97EBE3)
val onPrimaryDarkMediumContrast = Color(0xFF002B28)
val primaryContainerDarkMediumContrast = Color(0xFF489E97)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFC6E2DE)
val onSecondaryDarkMediumContrast = Color(0xFF102A27)
val secondaryContainerDarkMediumContrast = Color(0xFF7B9693)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC5DFFD)
val onTertiaryDarkMediumContrast = Color(0xFF0B273F)
val tertiaryContainerDarkMediumContrast = Color(0xFF7A93AF)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1514)
val onBackgroundDarkMediumContrast = Color(0xFFDDE4E2)
val surfaceDarkMediumContrast = Color(0xFF0E1514)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3F4947)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD4DEDC)
val outlineDarkMediumContrast = Color(0xFFAAB4B2)
val outlineVariantDarkMediumContrast = Color(0xFF889291)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE4E2)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2A)
val inversePrimaryDarkMediumContrast = Color(0xFF00514C)
val surfaceDimDarkMediumContrast = Color(0xFF0E1514)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4645)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040808)
val surfaceContainerLowDarkMediumContrast = Color(0xFF181F1E)
val surfaceContainerDarkMediumContrast = Color(0xFF232928)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2D3433)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF383F3E)

val primaryDarkHighContrast = Color(0xFFACFFF6)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF7DD1C9)
val onPrimaryContainerDarkHighContrast = Color(0xFF000E0C)
val secondaryDarkHighContrast = Color(0xFFDAF6F2)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFADC8C4)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0C)
val tertiaryDarkHighContrast = Color(0xFFE7F1FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFABC5E3)
val onTertiaryContainerDarkHighContrast = Color(0xFF000C1A)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF0E1514)
val onBackgroundDarkHighContrast = Color(0xFFDDE4E2)
val surfaceDarkHighContrast = Color(0xFF0E1514)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F4947)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFE8F2F0)
val outlineVariantDarkHighContrast = Color(0xFFBAC5C3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDDE4E2)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF00514C)
val surfaceDimDarkHighContrast = Color(0xFF0E1514)
val surfaceBrightDarkHighContrast = Color(0xFF4B5150)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1A2120)
val surfaceContainerDarkHighContrast = Color(0xFF2B3231)
val surfaceContainerHighDarkHighContrast = Color(0xFF363D3C)
val surfaceContainerHighestDarkHighContrast = Color(0xFF414847)







